# Generated by Django 5.1.5 on 2025-04-01 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectly_api', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
